name: React CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

defaults:
  run:
    working-directory: ReactJS_Advance/Final Capstone/Capstone-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
