name: React CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ReactJS_Advance/Day2_StateManagement/state_management

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

          cache-dependency-path: ./ReactJS_Advance/Day2_StateManagement/state_management/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npx vitest run
      - run: npm run build
